### ISSUE TITLE
Error: Cannot find module 'total.js/utils'

### ISSUE THREAD

**Issue by joshuataylor** [totaljs/framework#178]
When running "node debug.js":

``` javascript
module.js:340
    throw err;
          ^
Error: Cannot find module 'total.js/utils'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at app (/home/josh/something/debug.js:12:376)
    at Object.<anonymous> (/home/josh/something/debug.js:12:3232)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

This is following the instructions on the readme.

**Comment by kevinriver** [comment]
`npm install -g total.js`
after global install, i still has the same error.
`{ Error: Cannot find module 'total.js/utils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at app (d:\workspace\nodejsdevelop\company\debug.js:17:2764)
    at run (d:\workspace\nodejsdevelop\company\debug.js:17:3815)
    at Object.<anonymous> (d:\workspace\nodejsdevelop\company\debug.js:17:4314)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }`

**Comment by petersirka** [comment]
Hi @kevinriver,
I updated info a few days ago in Total.js documentation:

__Peter Sirka's configuration__:

```html
/my-app-folder/
/my-app-folder/node_modules/ <!-- create it manually and this directory will contain all Node.js modules -->

/my-app-folder/apps/ <!-- directory will contain your Total.js apps, e.g: -->
/my-app-folder/apps/totaljs_com-www/
/my-app-folder/apps/componentator_com-www/
/my-app-folder/apps/...
```

How can I install Total.js?

```bash
cd /my-app-folder/
npm install total.js
```

__Safe configuration__:

```html
/apps/ <!-- directory will contain your Total.js apps, e.g: -->

/apps/totaljs_com-www/
/apps/totaljs_com-www/node_modules <!-- create it manually and this directory will contain all Node.js modules for this app -->

/apps/componentator_com-www/
/apps/componentator_com-www/node_modules <!-- create it manually and this directory will contain all Node.js modules for this app -->
/apps/...
```

How can I install Total.js?

```bash
cd /apps/totaljs_com-www/
npm install total.js
```

---

https://youtu.be/mE9cavUIMQY?t=20s

**Comment by netAction** [comment]
I had still the same issue. The „Safe configuration“ works.

**Comment by petersirka** [comment]
__I have updated documentation about it:__
<https://docs.totaljs.com/latest/en.html#pages~Getting%20started~(recommendation-for-directory-structure)>

Thank you.
