### ISSUE TITLE
ImageMagick error

### ISSUE THREAD

**Issue by dacrhu** [totaljs/framework#246]
Hi,

I put from documents this code to my project:

var Image = require('total.js/image');
var image = Image.load('filename', [imageMagick]);

Result:
======= 2015-01-29 15:24:26: ReferenceError: imageMagick is not defined ReferenceError: imageMagick is not defined
    at thumbnail (/home/berci/napigif/GIT/controllers/controller-index.js:32:59)
    at Query._callback (/home/berci/napigif/GIT/controllers/controller-index.js:22:13)
    at Query.Sequence.end (/home/berci/napigif/GIT/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/home/berci/napigif/GIT/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/home/berci/napigif/GIT/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/home/berci/napigif/GIT/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/home/berci/napigif/GIT/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/home/berci/napigif/GIT/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/berci/napigif/GIT/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)

\# yum list installed | grep -i imagemagick
ImageMagick.x86_64                     6.8.8.10-5.fc21                 installed
ImageMagick-c++.x86_64                 6.8.8.10-5.fc21                 installed
ImageMagick-libs.x86_64                6.8.8.10-5.fc21                 installed

What could be the problem?
Thank you,
David.

**Comment by petersirka** [comment]
Hi @dacrhu,

Add it into `config`
```plain
default-image-converter       : im
```

```js
var image = Image.load('filename');
```

Thanks.

**Comment by dacrhu** [comment]
Mea culpa, sorry :)
Other solution:
var image = Image.load('filename', true);

**Comment by petersirka** [comment]
Yes! :+1:
