### ISSUE TITLE
Package doesn't work

### ISSUE THREAD

**Issue by admorphit** [totaljs/framework#256]
Hi @petersirka

Following instructions at

   http://docs.totaljs.com/v1.7.x/en.html#pages~Packages

to create a package and fails when accessing

   http://localhost:8000/hello-world/

with error

   500: Internal Server Error

Below is server error
```
======= 2015-03-16 22:18:44: Error: View "layout" not found. ([object Object]) Error: View "layout" not found.
    at Object.Controller.view (/app/node_modules/total.js/index.js:5:31521)
    at Object.Controller.view (/app/node_modules/total.js/index.js:6:1078)
    at Object.view_greeting (/app/tmp/helloworld/index.js:14:10)
    at Subscribe.doExecute (/app/node_modules/total.js/index.js:4:20393)
    at Subscribe.execute (/app/node_modules/total.js/index.js:4:18974)
    at Subscribe.prepare (/app/node_modules/total.js/index.js:4:20048)
    at Subscribe.doEnd (/app/node_modules/total.js/index.js:4:21579)
    at IncomingMessage.<anonymous> (/app/node_modules/total.js/index.js:4:17386)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
```
Thoughts on why this happens?

**Comment by petersirka** [comment]
Hi @admorphit,
I assumed that you'll have own layout in `views` directory. Because I want to inject a package view to your layout. Try to create `layout.html` file into `/app/views/` directory.

Thanks.
Give me a feedback.

**Comment by admorphit** [comment]
Thanks, it works- found that can also fix by adding `default-layout: app` in `config` file.

Looks like command
`npm install total.js --save`
uses `app.html` in the folder `/app/views` instead of `layout.html` which caused the problem.

Keep improving totaljs!

**Comment by petersirka** [comment]
Thanks :-)
