### ISSUE TITLE
MongoDB error without internet

### ISSUE THREAD

**Issue by sarankup** [totaljs/framework#284]
Hi,

I make sure that MongoDB running before I start the framework {node.exe debug.js}. However, I see the below error *always*, ie., MongoDB connection is not established. However, if I connect to the Internet first before I start the {node.exe debug.js} then there are not errors in MongoDB connection and everything works well.

It seems I could not develop when I am in offline. Please advise, how to solve this issue? Here goes the error verbose.

```
======= 2015-05-14 22:25:02: monogodefault ---> TypeError: Cannot read property
'collection' of null ([object Object]) TypeError: Cannot read property 'collection' of null
    at EventEmitter.framework.database (C:\Users\ksaravana\Dropbox\landmark\definitions\mongodb.js:9:25)
    at Object.getposts (C:\Users\ksaravana\Dropbox\landmark\controllers\monogodefault.js:151:15)
    at Subscribe.doExecute (C:\Users\ksaravana\Dropbox\landmark\node_modules\total.js\index.js:7352:28)
    at Subscribe.execute (C:\Users\ksaravana\Dropbox\landmark\node_modules\total.js\index.js:7271:21)
    at Subscribe.prepare (C:\Users\ksaravana\Dropbox\landmark\node_modules\total.js\index.js:7331:10)
    at Subscribe.doEnd (C:\Users\ksaravana\Dropbox\landmark\node_modules\total.js\index.js:7420:14)
    at IncomingMessage.<anonymous> (C:\Users\ksaravana\Dropbox\landmark\node_modules\total.js\index.js:7193:14)
```

**Comment by petersirka** [comment]
Hi @sarankup,
can you show me some code from `definitions/mongodb.js` and `controllers/monogodefault.js`? Just send me e-mail.

Thanks!

**Comment by sarankup** [comment]
Here is my mongodb.js
```
var MC=require('mongodb').MongoClient;
var DB=null;
MC.connect('mongodb://localhost:27017/landmarkcity',function(err,db){
if(err) throw err;
DB=db;
});

framework.database=function(collection){
if(collection) return DB.collection(collection);
return DB;
};
```

mongodefault.js
```
var stringmodel=require('string');
var ObjectId=require('mongodb').ObjectID;
var email=require('total.js/mail');
email.on('error',function(err){console.log(err);});
var nodemailer=require('nodemailer');
var mailtransporter=nodemailer.createTransport({service: 'Gmail',auth: {user: 'landmarkcityapp@gmail.com',pass: 'Syl17052012'}});

var async=new Utils.Async();
var gi=0;
var dbvalues={};

exports.install = function(framework){
    framework.route('/db',view_db);
    framework.route('/newadd',new_add);
    framework.route('/postsubmit',postsubmit,['post','xss']);
    framework.route('/contactpagesubmit',contactpagesubmit,['post','#session']);
};

```

**Comment by petersirka** [comment]
Please send me the code in `controllers/mongodefault.js` between 140-160 lines.
Thanks.

**Comment by sarankup** [comment]
```
function showhome(){
    var self=this;
    self.view('home',self.body);
}

function getposts(){
    var self=this;
    framework.database('pure').find().limit(10).toArray(function(err,docs){
        if(err){self.json({success:true});}
        else{self.json(docs);}
    });
}

function getmyposts(){
    var self=this;
    framework.database('pure).find().limit(10).toArray(function(err,docs){
        if(err){self.json({success:true});}
        else{self.json(docs);}
    });
}
````

**Comment by petersirka** [comment]
OK, I don't see any problem. Only way how to prevent this problem is add a sleep time into `debug.js`.

__Update debug.js / release.js__:

```javascript
// ===================================================
// IMPORTANT: only for development
// total.js - web application framework for node.js
// http://www.totaljs.com
// ===================================================

var fs = require('fs');
var options = {};

// options.ip = '127.0.0.1';
// options.port = parseInt(process.argv[2]);
// options.config = { name: 'total.js' };
// options.https = { key: fs.readFileSync('keys/agent2-key.pem'), cert: fs.readFileSync('keys/agent2-cert.pem')};

// HERE:
options.sleep = 3000;
...
```

Please give me a feedback. I have a similar problem on my server (sometimes).

**Comment by sarankup** [comment]
Well. Does this mean it is not anything about internet connection in the computer? Is the problem occurs because my home page (first page of the my application) using database connection?

**Comment by petersirka** [comment]
Here is another way:

```javascript
var isOnline = false;

MC.connect('mongodb://localhost:27017/mydatabase',function(err,db) {
    if(err) throw err;
    DB=db;
    isOnline = true;
});

F.middleware('online', function(req, res, next) {
    if (isOnline)
        return next();
    res.send('OFFLINE');
    next = null;
});

F.use('online');
```
