### ISSUE TITLE
Cannot read property 'close' 

### ISSUE THREAD

**Issue by Geocloud** [totaljs/framework#300]
Hello,

Sometimes, i lost my internet connection and the load pages is very slow.
When i stop my application, i have this error:

======= 2015-07-19 13:46:12: TypeError: Cannot read property 'close' of null TypeError: Cannot read property 'close' of null
    at EventEmitter.Framework.stop (/Users/desk/GeoDesk/node_modules/total.js/index.js:1:9186)
    at process.<anonymous> (/Users/desk/GeoDesk/node_modules/total.js/index.js:6:31279)
    at process.emit (events.js:104:17)
    at Signal.wrap.onsignal (node.js:655:46)

**Comment by petersirka** [comment]
Hi Julien,
can you use beta version for your project? `npm install total.js@beta`
I need error log again. Thanks.
