### ISSUE TITLE
[Error: Not running]

### ISSUE THREAD

**Issue by LeventeNagy** [totaljs/framework#313]
Hello Peter.

I dont know if something worng with my part.

But when i first start total js all okay.

If i try to close it i get the following error.

<pre>
[Error: channel closed]
======= 2015-08-23 15:39:04: Error: channel closed Error: channel closed
    at process.target.send (child_process.js:402:26)
    at EventEmitter.Framework.stop (/home/levente/node/total/node_modules/total.js/index.js:614:11)
    at process.on.Utils.wait.framework.console (/home/levente/node/total/node_modules/total.js/index.js:13778:12)
    at process.EventEmitter.emit (events.js:95:17)

</pre>

After i restart, no matter if release or debug, every time i make a change i get the following error

<pre>
======= 2015-08-23 15:39:04: Error: channel closed Error: channel closed
    at process.target.send (child_process.js:402:26)
    at EventEmitter.Framework.stop (/home/levente/node/total/node_modules/total.js/index.js:614:11)
    at process.on.Utils.wait.framework.console (/home/levente/node/total/node_modules/total.js/index.js:13778:12)
    at process.EventEmitter.emit (events.js:95:17)

</pre>

If i close the terminal, run release or debug all ok, but i soon as i close everything fails

**Comment by petersirka** [comment]
Hi @LeventeNagy,
please try the latest beta version `npm install total.js@beta` and give me a feedback with the console output if the problem will persist.

Thanks.

**Comment by LeventeNagy** [comment]
Sorry for the slow reply @petersirka 

Installed the latest beta. Still the same results

<pre>
[Error: Not running]
======= 2015-08-24 13:09:55: Error: Not running Error: Not running
    at Server.close (net.js:1233:11)
    at EventEmitter.Framework.stop (/home/levente/node/total/node_modules/total.js/index.js:622:15)
    at process.on.Utils.wait.framework.console (/home/levente/node/total/node_modules/total.js/index.js:13955:12)
    at process.EventEmitter.emit (events.js:95:17)
    at process.exit (node.js:707:17)
    at EventEmitter.Framework.stop (/home/levente/node/total/node_modules/total.js/index.js:624:10)
    at process.on.Utils.wait.framework.console (/home/levente/node/total/node_modules/total.js/index.js:13951:12)
    at process.EventEmitter.emit (events.js:92:17)
    at Signal.wrap.onsignal (node.js:757:46)
[Error: Not running]
levente@levente:~/node/total$ ======= 2015-08-24 13:09:55: Error: Not running Error: Not running
    at Server.close (net.js:1233:11)
    at EventEmitter.Framework.stop (/home/levente/node/total/node_modules/total.js/index.js:622:15)
    at process.on.Utils.wait.framework.console (/home/levente/node/total/node_modules/total.js/index.js:13947:12)
    at process.EventEmitter.emit (events.js:92:17)
    at Signal.wrap.onsignal (node.js:757:46)
[Error: channel closed]
======= 2015-08-24 13:09:57: Error: channel closed Error: channel closed
    at process.target.send (child_process.js:402:26)
    at EventEmitter.Framework.stop (/home/levente/node/total/node_modules/total.js/index.js:617:11)
    at process.on.Utils.wait.framework.console (/home/levente/node/total/node_modules/total.js/index.js:13955:12)
    at process.EventEmitter.emit (events.js:95:17)
</pre>

**Comment by petersirka** [comment]
Hmm can you send me a whole example on my e-mail?
I want to publish a new version but I'll wait for solve this problem.

Thanks.

**Comment by LeventeNagy** [comment]
One quick question before i send you the e-mail, could it be a problem that i am using linux? Just asking

**Comment by petersirka** [comment]
No, I have 4 Linux Ubuntu servers with more than 25 total.js projects in production.

**Comment by LeventeNagy** [comment]
Okay than, sending email

**Comment by petersirka** [comment]
The problem was solved.

**Comment by zixd** [comment]
Hi, Peter!
I had the same problem of LeventeNagy!
I also tried with the empty project (https://github.com/totaljs/framework/releases/download/v1.8.0/empty-project.zip) but I got the same error.
Could you tell me how did you solve this issue?
Thanks!
Have a nice day!

P.S.: Great framework!

**Comment by petersirka** [comment]
Hi @zixd,
@LeventeNagy wrote me: `Removed re-installed via command line, now it works fine`.

__My questions for you__:
1. Which version and distribution of linux do you have?
2. Please try to install latest version of node.js

Thanks and thanks for your compliment, I appreciate it.

**Comment by zixd** [comment]
Solved! With the latest version of node.js (v0.12.7) no more bugs!!!
Thanks again! Great help!
Bye!

**Comment by petersirka** [comment]
Great! Thanks too.
