### ISSUE TITLE
I installed total.js globally but cannot be imported in my code

### ISSUE THREAD

**Issue by metalvexis** [totaljs/framework#433]
I installed totalJs globally with this:
npm install -g total.js

but when i load my app, this error appears:

C:\Users\hp\AppData\Roaming\npm\total.js:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\github\totaljs\examples\websocket\index.js:7:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by metalvexis** [comment]
PS: here is the code of my app

var test_pack = require('total.js');
console.log(test_pack);

It can never be any simpler than that, does it?

**Comment by petersirka** [comment]
@metalvexis how do you run this app? I mean: which command did you use in command-line?

Thank you.

**Comment by metalvexis** [comment]
via command-line:
node test.js


btw, i explored the install path of the packages. i deleted the .cmd files that is outside the node_modules folder.
i.e. total.cmd, total.js.cmd etc..
the test app works now but i dont understand why and how it worked.

**Comment by petersirka** [comment]
Hmmm, it's really interesting. Try to install latest version of Node.js `+4`. I use macOS only so if you find a problem, contact me.
