### ISSUE TITLE
View Engine undefined variable

### ISSUE THREAD

**Issue by Athuli7** [totaljs/framework#453]
When the view engine fails, there is no indication of where the error occurred. It would be useful if the **line number** where displayed.

Log of such an error :-
======= 2016-11-18 07:41:41: default ---> Error: View: blog_post - TypeError: Cannot read property 'name' of undefined (http://localhost:9000/blog/firstpost) Error: View: blog_post - TypeError: Cannot read property 'name' of undefined
    at Object.Controller.view (H:\PLCCKochi\Totaljs_v1\node_modules\TOTAL.JS\INDEX.JS:12647:13)
    at Object.view_blog_post (H:\PLCCKochi\Totaljs_v1\controllers\DEFAULT.JS:76:7)
    at Subscribe.doExecute (H:\PLCCKochi\Totaljs_v1\node_modules\TOTAL.JS\INDEX.JS:9605:23)
    at Subscribe.execute (H:\PLCCKochi\Totaljs_v1\node_modules\TOTAL.JS\INDEX.JS:9531:8)
    at Subscribe.prepare (H:\PLCCKochi\Totaljs_v1\node_modules\TOTAL.JS\INDEX.JS:9572:8)
    at Subscribe.doEnd (H:\PLCCKochi\Totaljs_v1\node_modules\TOTAL.JS\INDEX.JS:9684:8)
    at IncomingMessage.self.req.on (H:\PLCCKochi\Totaljs_v1\node_modules\TOTAL.JS\INDEX.JS:9468:32)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)

**Comment by petersirka** [comment]
Hi @Athuli7,
- which version of Total.js do you use?
- do you use `debug` mode?

**Comment by Athuli7** [comment]
Node.js     : v6.3.1
Total.js    : v2.2.0
OS          : win32 10.0.14393
Mode        : debug

Event : Incorrect call of variables in view.
Issue : While the variable being accessed is mentioned, there is no info about the parent.

Error Log :-
500: Internal Server Error :: Error: View: blog_index - TypeError: Cannot read property 'data' of undefined
    at Object.Controller.view (H:\PLCCKochi\Totaljs_v1\node_modules\TOTAL.JS\index.js:12647:13)
    at Object.view_blog_index (H:\PLCCKochi\Totaljs_v1\controllers\default.js:41:7)
    at Subscribe.doExecute (H:\PLCCKochi\Totaljs_v1\node_modules\TOTAL.JS\index.js:9605:23)
    at Subscribe.execute (H:\PLCCKochi\Totaljs_v1\node_modules\TOTAL.JS\index.js:9531:8)
    at Subscribe.prepare (H:\PLCCKochi\Totaljs_v1\node_modules\TOTAL.JS\index.js:9572:8)
    at Subscribe.doEnd (H:\PLCCKochi\Totaljs_v1\node_modules\TOTAL.JS\index.js:9684:8)
    at IncomingMessage.self.req.on (H:\PLCCKochi\Totaljs_v1\node_modules\TOTAL.JS\index.js:9468:32)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)

**Comment by petersirka** [comment]
Can I see the view?

**Comment by Athuli7** [comment]
@petersirka, just make any view and add a variable that doesn't exist.

In the example below, if repository.entity resolves to something that isn't the child of advocates, then a 500 is thrown. But the error would say, could not resolve proexpContent of undefined.
In large views, with generic titles and large models, it becomes hard to debug.

```
      <div class="cp-experience padding-btm-60">
        <div class="container">
          <h3>Professional Experience</h3>
          @{!repository.data.advocate[repository.entity].proexpContent}
        </div>
      </div>
```

And if you are very particular about the seeing the whole view, it has been attached.

[advocate_details.zip](https://github.com/totaljs/framework/files/599500/advocate_details.zip)

**Comment by petersirka** [comment]
It's not good idea to use `repository.data.advocate[repository.entity]` ... Why don't you prepare data before rendering?

```javascript
var repository = self.repository;
var model = repository.data && repository.data.advocate && repository.data.advocate[repository.entity];

if (!model)
    return self.throw404();

self.view('advocate_details', model);
```

I found a bug in the view engine compiler. I'm going to fix it.

**Comment by petersirka** [comment]
I have fixed it. Try it: `npm install total.js@beta` (don't worry and it's stable - maybe next week will be a new version).

Thank you!

**Comment by Athuli7** [comment]
Preparing data... most pages rendered have almost 5/6 interconnected datasets.
I found it easier to dump the whole thing to the repository.
I understand it's a lazy fix, but it's a small work with a very small static JSON dataset..

**Comment by Athuli7** [comment]
Thanks for the fix.
About using the beta channel, wouldn't that be an issue once the version is rolled out and you start development on the new version ?
Or is beta generally a very stable build that is named so, to avoid pile up of issues and/or version number pile up.

**Comment by petersirka** [comment]
Beta still contains latest dev branch and this beta is stable (yet). 👍
