### ISSUE TITLE
builder.join error when only 1 record selected

### ISSUE THREAD

**Issue by yexing** [totaljs/framework#462]
It is a clear mistake in onsql.js line 1301. When response is not an array, the 'join' is undefined. I think it should be

````javascript
	} else if (response) {
			var item = response; // :)
			for (var j = 0; j < jl; j++) {
				var join = self.$join[keys[j]];
				item[join.field] = join.scalar ? scalar(join.items, join.scalar, join.scalarfield, join.a, join.b != null ? item[join.b] : undefined) : join.first ? findItem(join.items, join.a, item[join.b], join.scalar, join.scalarfield) : findItems(join.items, join.a, item[join.b]);
			}
		// response[join.field] = join.scalar ? scalar(join.items, join.scalar, join.scalarfield, join.a, join.b != null ? response[join.b] : undefined) : join.first ? findItem(join.items, join.a, response[join.b]) : findItems(join.items, join.a, response[join.b]);
	}

````

**Comment by petersirka** [comment]
Hi @yexing,
can you show me a full error message? ... and can you show me your code to call a DB?

Thank you very much!

**Comment by yexing** [comment]
code:

        NOSQL("tournaments").find().make(function(builder) {
            builder.first()
            builder.where('id', model.id)
            builder.join("teams", "tour_team").where("tour_id", "id")
            builder.callback(function(err, response) {
                self.json(response)
            });
        });

error:

TypeError: Cannot read property 'field' of undefined
    at DatabaseBuilder.$callback2 (/Users/shinno/node_modules/total.js/nosql.js:1301:16)
    at Immediate.setImmediate (/Users/shinno/node_modules/total.js/nosql.js:1285:27)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
