### ISSUE TITLE
create new project

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/framework#514]
Hi!
I have this error when create a new project.
node -v 7.10.0
```cmd
E:\total\kk>total

|==================================================|
| Total.js - Web framework for Node.js             |
| Version: v2.5.0-9                                |
|==================================================|

Downloading "empty-project" from www.totaljs.com
======= 2017-06-12 15:53:46: TypeError: Cannot read property 'pipe' of undefined TypeError: Cannot read property 'pipe' of undefined
    at Object.callback (C:\Users\puchadri\AppData\Roaming\npm\node_modules\total.js\bin\totaljs:664:11)
    at ClientRequest.<anonymous> (C:\Users\puchadri\AppData\Roaming\npm\node_modules\total.js\utils.js:876:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
======= 2017-06-12 15:53:46: TypeError: Cannot read property 'pipe' of undefined TypeError: Cannot read property 'pipe' of undefined
    at Object.callback (C:\Users\puchadri\AppData\Roaming\npm\node_modules\total.js\bin\totaljs:664:11)
    at ClientRequest.<anonymous> (C:\Users\puchadri\AppData\Roaming\npm\node_modules\total.js\utils.js:876:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketCloseListener (_http_client.js:334:9)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:191:7)
    at _handle.close (net.js:511:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7)
```

**Comment by petersirka** [comment]
Hi @adrianrey05,
please try to install Total.js again as a global module `$ npm install -g total.js`. You have older version. Give me a feedback.

**Comment by adrianrey05** [comment]
Hi @petersirka,
look, when i try install total.js
```cmd

C:\Users\puchadri>npm install -g total.js
C:\Users\puchadri\AppData\Roaming\npm\totaljs -> C:\Users\puchadri\AppData\Roaming\npm\node_modules\total.js\bin\totaljs
C:\Users\puchadri\AppData\Roaming\npm\total.js -> C:\Users\puchadri\AppData\Roaming\npm\node_modules\total.js\bin\totaljs
C:\Users\puchadri\AppData\Roaming\npm\totalpackage -> C:\Users\puchadri\AppData\Roaming\npm\node_modules\total.js\bin\tpm
C:\Users\puchadri\AppData\Roaming\npm\total -> C:\Users\puchadri\AppData\Roaming\npm\node_modules\total.js\bin\totaljs
C:\Users\puchadri\AppData\Roaming\npm\tpm -> C:\Users\puchadri\AppData\Roaming\npm\node_modules\total.js\bin\tpm
C:\Users\puchadri\AppData\Roaming\npm
`-- total.js@2.4.0

```

**Comment by petersirka** [comment]
Hmmm, latest version is 2.6.2:
https://www.npmjs.com/package/total.js

![image](https://user-images.githubusercontent.com/2414252/27050976-b73067d2-4fb4-11e7-8b09-32ba58619b13.png)

Which version of Node.js have you got?

**Comment by adrianrey05** [comment]
i have node -v 7.10.0

**Comment by petersirka** [comment]
It's very interesting. Try to install `$ npm install total.js@2.6.2`.

**Comment by adrianrey05** [comment]
i resolve with Yarn
```cmd
yarn global add total.js
yarn global v0.24.6
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "total.js@2.6.2" with binaries:
      - total
      - total.js
      - totaljs
      - tpm
      - totalpackage
warning No license field
Done in 9.90s.
```

thanks  @petersirka
