### ISSUE TITLE
TypeError: file.onValidate.call is not a function

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#521]
I want to download .obj file from server. Here is my code:
```
const path = require('path')
const fs = require('fs')
exports.install = function() {
	F.file('/3d/', file_test, ['.obj'])
}

function file_test (req, res) {
	const filename = path.basename(req.url)
	const filepath = path.join('3d', filename)
	this.file(filepath)
}
```
I put my .obj file under public/3d/ directory, I got these error (even when loading favicon !)
```
======= 2017-07-13 12:58:04: unknown ---> TypeError: file.onValidate.call is not a function (http://localhost:8000/3d/124.obj) TypeError: file.onValidate.call is not a function
    at IncomingMessage.PROTO.$total_endfile (/Users/ckpiggy/Documents/JS/three_360/node_modules/total.js/index.js:13836:52)
    at IncomingMessage.subscribe_file (/Users/ckpiggy/Documents/JS/three_360/node_modules/total.js/index.js:9097:7)
    at IncomingMessage.PROTO.$total_file (/Users/ckpiggy/Documents/JS/three_360/node_modules/total.js/index.js:13507:19)
    at Object.F.$requestcontinue (/Users/ckpiggy/Documents/JS/three_360/node_modules/total.js/index.js:6361:8)
    at Server.F.listener (/Users/ckpiggy/Documents/JS/three_360/node_modules/total.js/index.js:6336:5)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
======= 2017-07-13 12:58:04: unknown ---> TypeError: file.onValidate.call is not a function (http://localhost:8000/favicon.ico) TypeError: file.onValidate.call is not a function
    at IncomingMessage.PROTO.$total_endfile (/Users/ckpiggy/Documents/JS/three_360/node_modules/total.js/index.js:13836:52)
    at IncomingMessage.subscribe_file (/Users/ckpiggy/Documents/JS/three_360/node_modules/total.js/index.js:9097:7)
    at IncomingMessage.PROTO.$total_file (/Users/ckpiggy/Documents/JS/three_360/node_modules/total.js/index.js:13507:19)
    at Object.F.$requestcontinue (/Users/ckpiggy/Documents/JS/three_360/node_modules/total.js/index.js:6361:8)
    at Server.F.listener (/Users/ckpiggy/Documents/JS/three_360/node_modules/total.js/index.js:6336:5)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

```
But it will be good if I change the action function to plain nodejs:
```
function file_test (req, res) {
	const filename = path.basename(req.url)
	const filePath = path.join( __dirname,'..', CONFIG('directory-public'),'3d', filename)
	const read = fs.createReadStream(filePath)
	read.pipe(res)
}
```

**Comment by petersirka** [comment]
Hi @ckpiggy,

```javascript
function file_test (req, res) {
    const filename = path.basename(req.url)
    const filepath = path.join('3d', filename)

    // This is the problem because "this" is not a context of controller
    // Filehandler needs to use methods in "res" object
    // BAD: this.file(filepath)
    res.file(filepath);
}
```
I'll try to fix error message.

**Comment by ckpiggy** [comment]
It works!! Thank you.

It will be nice to note the action functions of `F.route` and `F.file` have different context in document.

**Comment by ckpiggy** [comment]
Oops! I have to change the filepath to get the solution work. 
```
function files_3d (req, res) {
	const filename = path.basename(req.url)
	const filepath = path.join( __dirname,'..', CONFIG('directory-public'),'3d', filename)
	res.file(filepath)
}
```
