### ISSUE TITLE
framework test failed with 'Error: View "precompile.homepage" not found.'

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#525]
I forked the framework and execute the `run.sh` in `test/`.
And I got 
```
Error: View "precompile.homepage" not found.
    at Controller.$viewrender (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:11642:9)
    at Controller.view (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:11622:14)
    at Controller.view_precomile (/Users/ckpiggy/Documents/JS/totaljs_framework/test/controllers/default.js:152:7)
    at IncomingMessage.PROTO.$total_execute2 (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13344:32)
    at IncomingMessage.PROTO.$total_execute (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13314:9)
    at IncomingMessage.PROTO.$total_authorize (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13432:10)
    at /Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13599:9
    at framework.onAuthorize (/Users/ckpiggy/Documents/JS/totaljs_framework/test/test-framework-release.js:35:2)
    at IncomingMessage.PROTO.$total_prepare (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13587:4)
    at IncomingMessage.PROTO.$total_end2 (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13458:9) 'default' { auth: null,
  hash: null,
  host: '127.0.0.1:8001',
  hostname: '127.0.0.1',
  href: 'http://127.0.0.1:8001/precompile/',
  path: '/precompile/',
  pathname: '/precompile/',
  port: '8001',
  protocol: 'http:',
  query: null,
  search: null,
  slashes: true }
```

Did I miss something?

**Comment by petersirka** [comment]
```bash
$ cd framework/test
$ bash run.sh
```

Thank you!

**Comment by ckpiggy** [comment]
I found if I test again just after the test finished I got the same errors. 
But if I test after the test ended about 10 secs, there are no errors.
It is not related to `bash` command.
The error occur when running
```
node --harmony test-framework-debug.js
node --harmony test-framework-release.js
```
The error message when I use `bash run.sh` just after previous test ended.
```
====================================================
PID         : 10061
Node.js     : v6.11.1
Total.js    : v2.7.0
OS          : darwin 16.6.0
====================================================
Name        : Total.js
Version     : 1.0.0
Author      : 
Date        : 2017-07-25 09:30:57
Mode        : debug
====================================================

http://0.0.0.0:8001/

Error: View "precompile.homepage" not found.
    at Object.Controller.$viewrender (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:11642:9)
    at Object.view_precomile (/Users/ckpiggy/Documents/JS/totaljs_framework/test/controllers/default.js:152:7)
    at IncomingMessage.PROTO.$total_execute2 (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13344:32)
    at IncomingMessage.PROTO.$total_execute (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13314:9)
    at IncomingMessage.PROTO.$total_authorize (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13432:10)
    at /Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13599:9
    at framework.onAuthorize (/Users/ckpiggy/Documents/JS/totaljs_framework/test/test-framework-debug.js:35:2)
    at IncomingMessage.PROTO.$total_prepare (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13587:4)
    at IncomingMessage.PROTO.$total_end2 (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13458:9)
    at IncomingMessage.subscribe_end (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:8818:7) 'default' { auth: null,
  hash: null,
  host: '127.0.0.1:8001',
  hostname: '127.0.0.1',
  href: 'http://127.0.0.1:8001/precompile/',
  path: '/precompile/',
  pathname: '/precompile/',
  port: '8001',
  protocol: 'http:',
  query: null,
  search: null,
  slashes: true }
Error: View "precompile.homepage" not found.
    at Object.Controller.$viewrender (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:11642:9)
    at Object.view_precomile (/Users/ckpiggy/Documents/JS/totaljs_framework/test/controllers/default.js:152:7)
    at IncomingMessage.PROTO.$total_execute2 (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13344:32)
    at IncomingMessage.PROTO.$total_execute (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13314:9)
    at IncomingMessage.PROTO.$total_authorize (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13432:10)
    at /Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13599:9
    at framework.onAuthorize (/Users/ckpiggy/Documents/JS/totaljs_framework/test/test-framework-debug.js:35:2)
    at IncomingMessage.PROTO.$total_prepare (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13587:4)
    at IncomingMessage.PROTO.$total_end2 (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13458:9)
    at IncomingMessage.subscribe_end (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:8818:7)
{ AssertionError: framework.precompile() problem
    at Object.callback (/Users/ckpiggy/Documents/JS/totaljs_framework/test/test-framework-debug.js:412:11)
    at IncomingMessage.<anonymous> (/Users/ckpiggy/Documents/JS/totaljs_framework/utils.js:738:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'framework.precompile() problem',
  generatedMessage: false } '' null
AssertionError: framework.precompile() problem
    at Object.callback (/Users/ckpiggy/Documents/JS/totaljs_framework/test/test-framework-debug.js:412:11)
    at IncomingMessage.<anonymous> (/Users/ckpiggy/Documents/JS/totaljs_framework/utils.js:738:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
{ Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8001 } '' null
Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
{ Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketCloseListener (_http_client.js:285:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12) code: 'ECONNRESET' } '' null
Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketCloseListener (_http_client.js:285:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)
====================================================
PID         : 10063
Node.js     : v6.11.1
Total.js    : v2.7.0
OS          : darwin 16.6.0
====================================================
Name        : Total.js
Version     : 1.0.0
Author      : 
Date        : 2017-07-25 09:31:01
Mode        : release
====================================================

http://0.0.0.0:8001/

Error: View "precompile.homepage" not found.
    at Object.Controller.$viewrender (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:11642:9)
    at Object.view_precomile (/Users/ckpiggy/Documents/JS/totaljs_framework/test/controllers/default.js:152:7)
    at IncomingMessage.PROTO.$total_execute2 (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13344:32)
    at IncomingMessage.PROTO.$total_execute (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13314:9)
    at IncomingMessage.PROTO.$total_authorize (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13432:10)
    at /Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13599:9
    at framework.onAuthorize (/Users/ckpiggy/Documents/JS/totaljs_framework/test/test-framework-release.js:35:2)
    at IncomingMessage.PROTO.$total_prepare (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13587:4)
    at IncomingMessage.PROTO.$total_end2 (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13458:9)
    at IncomingMessage.subscribe_end (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:8818:7) 'default' { auth: null,
  hash: null,
  host: '127.0.0.1:8001',
  hostname: '127.0.0.1',
  href: 'http://127.0.0.1:8001/precompile/',
  path: '/precompile/',
  pathname: '/precompile/',
  port: '8001',
  protocol: 'http:',
  query: null,
  search: null,
  slashes: true }
Error: View "precompile.homepage" not found.
    at Object.Controller.$viewrender (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:11642:9)
    at Object.view_precomile (/Users/ckpiggy/Documents/JS/totaljs_framework/test/controllers/default.js:152:7)
    at IncomingMessage.PROTO.$total_execute2 (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13344:32)
    at IncomingMessage.PROTO.$total_execute (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13314:9)
    at IncomingMessage.PROTO.$total_authorize (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13432:10)
    at /Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13599:9
    at framework.onAuthorize (/Users/ckpiggy/Documents/JS/totaljs_framework/test/test-framework-release.js:35:2)
    at IncomingMessage.PROTO.$total_prepare (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13587:4)
    at IncomingMessage.PROTO.$total_end2 (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:13458:9)
    at IncomingMessage.subscribe_end (/Users/ckpiggy/Documents/JS/totaljs_framework/index.js:8818:7)
{ Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8001 } '' null
Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
{ Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketCloseListener (_http_client.js:285:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12) code: 'ECONNRESET' } '' null
Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketCloseListener (_http_client.js:285:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)
```

**Comment by petersirka** [comment]
This tests download some content from Total.js website, are you sure you have stable internet connection?
