### ISSUE TITLE
Upload Image Problem

### ISSUE THREAD

**Issue by DaisyMonte** [totaljs/framework#539]
Hello!

I'm trying to upload an image from the Angular to the Total without success.
I've tried it in several ways, but I always get the following error:

```
{ 
Error: Command failed: gm -convert "C:\...\tmp\uploadedfile-1.bin" +profile "*" -limit memory 450 -l
imit map 900 "C:\...\public\perfil.jpg"

    gm convert: Unable to open file (C:\...\tmp\uploadedfile-1.bin) [No such file or directory].
    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

  killed: false,
  code: 1,
  signal: null,
  cmd: 'gm -convert "C:\...\\tmp\\uploadedfile-1.bin" +profile "*" -limit memory 450 -limit map 900
  "C:\...\\public\\perfil.jpg"'
}
```

Route:
` F.route('/teacher/create/', action_create, ['teacher', 'upload', 'post', 'cors'], 100);`

Action:
```
function action_create() {
    let self = this;
    let file = self.files[0];
    let target = self.files[0].filename;
    file.image().make(function(image) {
        image.save(F.path.public(target), (error, isSaved) => {
            if (!isSaved) {
                console.log("Image not saved! ");
                console.log(error);
            }
        });
    });
}
```

CONSOLE.LOG self.files[0]

```
HttpFile {
  length: 70221,
  width: 600,
  height: 400,
  rem: true,
  '$data': undefined,
  '$step': undefined,
  '$is': undefined,
  name: 'foto',
  filename: 'perfil.jpg',
  path: 'C:/.../tmp/uploadedfile-0.bin',
  type: 'image/jpeg' }
```

My Custom FileUploaderComponent in Angular:
HTML 

```
<form [formGroup]="formGroup" (ngSubmit)="onSubmit()">
       <div class="form-group">
              ....
       </div>
        <div class="form-group">
              <img [src]="imageSrc" (load)="handleImageLoad()" [class.loaded]="imageLoaded" />
              <input type="file" name="file" accept="image/*" (change)="handleInputChange($event)">
       </div>
       <div class="form-group">
              ....
       </div>
</form>
```

TYPESCRIPT
```
handleInputChange(e) {
        let file: File = e.dataTransfer ? e.dataTransfer.files[0] : e.target.files[0];
        let pattern = /image-*/;
        
        if (!file.type.match(pattern)) {
            alert('invalid format');
            return;
        }
        this.loaded = false;
        this.reader = new FileReader();
        this.reader.onload = this._handleReaderLoaded.bind(this);
        this.reader.readAsDataURL(file);
        this.value = file;
}
```
```
private onSubmit(){
    let formGroup = this.formGroup.value;
    let teacher: Teacher= new Teacher(formGroup);
    let observable;
    if (this.new) {
        observable = this.teachersService.create(teacher);
    } else {
        observable = this.teachersService.update(this.id, teacher);
    }

    observable.subscribe(
      (teacher) => {
        console.log(teacher);
      },
      (error) =>  {
        console.log(error);
      }
    );
  }
```
And My Service:
```
this.baseUrl = "http://127.0.0.1:8000/teachers";
public create(teacher: Teacher): Observable<any> {
    let formData:FormData = new FormData();
    this.headers = new Headers({});
    this.options = new RequestOptions({ headers: this.headers});
    for(let key in teacher) {
      formData.append(key,  teacher[key]);
    }
    return this.http.post(this.baseUrl + '/create/', formData, this.options)
    .map(this.extractData)
    .catch(this.handleError)
}
```
Navigator Header Request:

```
Request Headers
Provisional headers are shown
Accept:application/json, text/plain, */*
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryQ3bZuGq6EomqBB69
Origin:http://localhost:4200
Referer:http://localhost:4200/docentes/novo
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

Request Payload
------WebKitFormBoundaryQ3bZuGq6EomqBB69
Content-Disposition: form-data; name="nome"

Daisy

------WebKitFormBoundaryQ3bZuGq6EomqBB69
Content-Disposition: form-data; name="email"

12@test.com

------WebKitFormBoundaryQ3bZuGq6EomqBB69
Content-Disposition: form-data; name="foto"; filename="perfil.jpg"
Content-Type: image/jpeg


------WebKitFormBoundaryQ3bZuGq6EomqBB69--
```

Thanks for all the help!!!

**Comment by DaisyMonte** [comment]
I got it!
Ignore that, it was stupid.
Change to:
```
Image.load(self.files[0]).make(function(image) {
        image.save(F.path.public(self.files[0].filename), (error, isSaved) => {
            if (!isSaved) {
                console.log("Image not saved! ");
                console.log(error);
            }
        });
    }); 
```

**Comment by petersirka** [comment]
I recommend to use <https://docs.totaljs.com/latest/en.html#api~HttpFile~file.image>:

```javascript
var file = self.files[0];
file.image().make(function(builder) {
     builder.quality(90);
     builder.minify();
     builder.save(F.path.public(file.filename, function(err, is) {

     });
});
```
Thank you.

**Comment by DaisyMonte** [comment]
Hi Peter!
This way, I get the following error:
Code:

```
let file = self.files[0];
    file.image().make(function(builder) {
        builder.quality(90);
        builder.minify();
        builder.save(F.path.public(self.files[0].filename), function(err, isSaved) {
            if (!isSaved) {
                body.foto = newName;
                console.log("Image not saved! ");
                console.log(err);
            } else {
                console.log("Saved! ");
            }
        });
    });

```

Console:
```
HttpFile {
  length: 70221,
  width: 600,
  height: 400,
  rem: true,
  '$data': undefined,
  '$step': undefined,
  '$is': undefined,
  name: 'foto',
  filename: 'perfil.jpg',
  path: 'C:/ProjetoLean/produtos-ensino-node/tmp/uploadedfile-0.bin',
  type: 'image/jpeg' }

Image not saved!
{ Error: Command failed: gm -convert "C:\ProjetoLean\produtos-ensino-node\tmp\uploadedfile-0.bin" +profile "*" -limit memory 450 -l
imit map 900 -quality 90 "C:\ProjetoLean\produtos-ensino-node\public\uploads\docente\04440985858-perfil.jpg"
gm convert: Unable to open file (C:\ProjetoLean\produtos-ensino-node\tmp\uploadedfile-0.bin) [No such file or directory].

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'gm -convert "C:\\ProjetoLean\\produtos-ensino-node\\tmp\\uploadedfile-0.bin" +profile "*" -limit memory 450 -limit map 900
-quality 90 "C:\\ProjetoLean\\produtos-ensino-node\\public\\uploads\\docente\\04440985858-perfil.jpg"' }
```
What am I doing wrong?
Thank you for the help!!

**Comment by petersirka** [comment]
I know where is the problem. I need to see your controller's action, put the whole code from the action please.

**Comment by DaisyMonte** [comment]
Is it?
Sorry, I do not know if I understood correctly.

```
F.route('/teachers/create/', action_create, ['upload', 'post', 'cors'], 100);

function action_create() {
    let self = this;
    let body = self.body;
    let newName = 'uploads/' + self.files[0].filename;

    let file = self.files[0];
    file.image().make(function(builder) {
        builder.quality(90);
        builder.minify();
        builder.save(F.path.public(newName), function(err, isSaved) {
            if (!isSaved) {
                console.log("Image not saved! ");
                console.log(err);
            } else {
                console.log("Saved! ");
            }
        });
    });

    Teacher.save(function(err, list) {
        if (err) {
            self.plain(err);
        } else {
            if (list) {
                self.json(list);
            } else {
                self.json({ err: "Erro na criação" });
            }
        }
    });
}
```

**Comment by petersirka** [comment]
Yes, correct.

- framework automatically removes all uploaded files when the action is responded
- `controller.noClear()` prevents removing of uploaded files
- `controller.clear()` removes uploaded files

```javascript
function action_create() {
    let self = this;
    let body = self.body;
    let newName = 'uploads/' + self.files[0].filename;
    let file = self.files[0];
    
    self.noClear(); // prevents clearing uploaded files

    file.image().make(function(builder) {
        builder.quality(90);
        builder.minify();
        builder.save(F.path.public(newName), function(err, isSaved) {
            self.clear(); // clears all uploaded files
            if (!isSaved) {
                console.log("Image not saved! ");
                console.log(err);
            } else {
                console.log("Saved! ");
            }
        });
    });

    Teacher.save(function(err, list) {
        if (err) {
            self.plain(err);
        } else {
            if (list) {
                self.json(list);
            } else {
                self.json({ err: "Erro na criação" });
            }
        }
    });
}
```

If you put `Teacher.save()` to `builder.save` callback then everything will work without `noClear()` and `clear()`. __BTW__: remove `cors` from routes and create a global CORS rule via <https://docs.totaljs.com/latest/en.html#api~Framework~F.cors>.

**Comment by DaisyMonte** [comment]
It's works!
Thank you very much!

How do I recover the file in the 'get' request?
Should I use file.read ()?

**Comment by petersirka** [comment]
Do you want to read a file in `get` request? If yes:

```javascript
F.file('/download/*.*', function(req, res) {
	res.file(F.path.root('debug.js'));
});
```

**Comment by DaisyMonte** [comment]
I would like to send the file along with a user query, for example:

```
F.route('/teachers/read/{id}', action_read, ['get']);

function action_read(id) {
    let self = this;
    if (!mongoose.Types.ObjectId.isValid(id)) {
        return res.status(400).json({ message: 'ID é inválido' });
    } else {
        Teacher.find({ _id: id },
            function(err, list) {
                if (err) {
                    self.plain(err);
                } else {
                    if (list) {
                        self.json(list);
                    } else {
                        self.json({ err: "Não Encontrado" });
                    }
                }
            });
    }
}
```

**Comment by petersirka** [comment]
I don't understand, I didn't see any file in your code. Why do you use `mongoose`? Your code is not clean for me, I recommend to use Total.js Schemas with SQL Agent with MongoDB.

**Comment by DaisyMonte** [comment]
Sorry, I did not explain clearly.

For now, I only get the object in mongodb.
I am saving the image url along with Schema.
In the request, I would like to return a file together.
I do not know if it is possible to include in the same request or if it is necessary to make a separate request.

Sorry, this is all new to me. I'm still learning.
And I apologize for my English too.

Teacher Schema: 

```
let mongoose = require('mongoose');
let uniqueValidator = require('mongoose-unique-validator');
let Schema = mongoose.Schema;

let validateEmail = function(email) {
    let re = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
    return re.test(email)
};

let teacherSchema = new Schema({
    name: {
        type: String,
        required: true,
        trim: true
    },
    link_lattes: {
        type: String,
        required: false,
        trim: true
    },
    email: {
        type: String,
        trim: true,
        lowercase: true,
        index: true,
        unique: "O endereço de e-mail já existe.",
        required: 'O endereço de e-mail é requerido.',
        validate: [validateEmail, 'Digite um endereço de e-mail válido.']
    },
    photo: {
        type: String
    },
    gender: {
        type: String,
        required: false,
        enum: ['male', 'female']
    }
}, {
    timestamps: {
        createdAt: 'created_at'
    }
});

exports.schema = mongoose.model('Teacher', teacherSchema);
exports.name = 'teacher';
```

**Comment by DaisyMonte** [comment]
I understand.
Thank you for responding so quickly and for all the help.
I'll try to use the recommended solution.
Total.js is great!
