### ISSUE TITLE
HTTP server

### ISSUE THREAD

**Issue by michalCapo** [totaljs/framework#577]
Hello,

I want to integrate horizon with totaljs. But I dont know how to get http server instance from total.js.

When i'm trying to get `F.server` i got:
```
/home/capo/n/bin/node[20610]: ../src/util-inl.h:243:TypeName* node::Unwrap(v8::Local<v8::Object>) [with TypeName = node::LibuvStreamWrap]: Assertion `(object->InternalFieldCount()) > (0)' failed.
 1: node::Abort() [total: total.js]
 2: node::Assert(char const* const (*) [4]) [total: total.js]
 3: void node::StreamBase::GetBytesRead<node::LibuvStreamWrap>(v8::Local<v8::String>, v8::PropertyCallbackInfo<v8::Value> const&) [total: total.js]
 4: v8::internal::PropertyCallbackArguments::Call(void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), v8::internal::Handle<v8::internal::Name>) [total: total.js]
 5: v8::internal::Object::GetPropertyWithAccessor(v8::internal::LookupIterator*) [total: total.js]
 6: v8::internal::Object::GetProperty(v8::internal::LookupIterator*) [total: total.js]
 7: v8::internal::JSReceiver::GetOwnPropertyDescriptor(v8::internal::LookupIterator*, v8::internal::PropertyDescriptor*) [total: total.js]
 8: v8::internal::JSReceiver::GetOwnPropertyDescriptor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDescriptor*) [total: total.js]
 9: v8::internal::Builtin_ObjectGetOwnPropertyDescriptor(int, v8::internal::Object**, v8::internal::Isolate*) [total: total.js]
10: 0x2dd2fa8441d
```

**Comment by petersirka** [comment]
Hi @michalCapo, can I see your initialization code?

**Comment by michalCapo** [comment]
```
const options = {};
require('total.js').http('release', options);
F.on('load', function () {
    F.server
});
```

**Comment by petersirka** [comment]
And where is the horizon integration?

**Comment by michalCapo** [comment]
Hmm i'm really sorry. It just happens only when i try "watch it" in my IDE (webstorm). Just printing it to console `console.log(F.server)` it works.

Right now there is no integration code. I was just trying find out 'how it could be done'.

**Comment by petersirka** [comment]
Does `horizon` use WebSocket?

**Comment by michalCapo** [comment]
Yes, internally.

I'm sorry for this issue, but at the end it works like a charm:

First you need to start `rethinkdb`

```
const options = {};

require('total.js').http('release', options);

F.on('load', function () {
    const horizon = require('@horizon/server');

    const options = {
        project_name: 'myProject',
        auto_create_collection: true,
        auto_create_index: true,
        auth: {
            token_secret: 'my_super_secret_secret'
        }
    };
    const horizonServer = horizon(F.server, options);

    console.log('Listening on port 8181.');
});
```

**Comment by michalCapo** [comment]
Hmm but debug doesn't work:
```
const options = {};

require('total.js/debug')(options);

F.on('load', function () {
    const horizon = require('@horizon/server');

    const options = {
        project_name: 'myProject',
        auto_create_collection: true,
        auto_create_index: true,
        auth: {
            token_secret: 'my_super_secret_secret'
        }
    };
    const horizonServer = horizon(F.server, options);

    console.log('Listening on port 8181.');
});
```

exception:
```
ReferenceError: F is not defined
    at Object.<anonymous> (/home/capo/my/code/emptyproject-website-master/debug.js:18:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
-------------------------> DEBUG PID: 31468 (v2.8.0)
ReferenceError: F is not defined
    at Object.<anonymous> (/home/capo/my/code/emptyproject-website-master/debug.js:18:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by petersirka** [comment]
You need to create a definition file e.g. `definitions/horizon.js`:

```javascript
const Horizon = require('@horizon/server');
const Options = {
    project_name: 'myProject',
    auto_create_collection: true,
    auto_create_index: true,
    auth: {
        token_secret: 'my_super_secret_secret'
    }
};

ON('load', function() {
    F.global.horizon = Horizon(F.server, Options);
    // or global.horizon = Horizon(...)
});
```

__Total.js/Debug__ creates a separated thread, it's a bit complicated to explain it.

**Comment by michalCapo** [comment]
ok, thanks. BTW: impresive response time.

**Comment by petersirka** [comment]
Thank you, Sometimes I'm faster, but today is weekend.
