### ISSUE TITLE
Endpoint called up to 4 times

### ISSUE THREAD

**Issue by gmenih341** [totaljs/framework#582]
I recently started working on a project written in TotalJS.

I seem to have a weird issue, where an API call will call the endpoint up to 4 times. Here's how I call the endpoint:

    $.components.GET('/api/endpoint/', options, function (response) {
        console.log(response);
    });

The endpoint handler is pretty simple, it basically does this:

    GETSCHEMA('Product').query(self.query, self.callback);

However, this gets called anywhere from 1 to 4 times. And the stack trace is always the same:

    at endpoint_handler (/home/grega/Projects/Work/totaljs_project/controllers/manager.js:1675:10)
    at PROTO.$total_execute2 (/home/grega/Projects/Work/totaljs_project/node_modules/total.js/index.js:13944:31)
    at PROTO.$total_execute (/home/grega/Projects/Work/totaljs_project/node_modules/total.js/index.js:13914:8)
    at PROTO.$total_authorize (/home/grega/Projects/Work/totaljs_project/node_modules/total.js/index.js:14032:9)
    at (anonymous) (/home/grega/Projects/Work/totaljs_project/node_modules/total.js/index.js:14195:8)
    at F.onAuthorize (/home/grega/Projects/Work/totaljs_project/models/users.js:201:2)
    at PROTO.$total_prepare (/home/grega/Projects/Work/totaljs_project/node_modules/total.js/index.js:14186:5)
    at PROTO.$total_end (/home/grega/Projects/Work/totaljs_project/node_modules/total.js/index.js:13855:8)
    at F.$requestcontinue (/home/grega/Projects/Work/totaljs_project/node_modules/total.js/index.js:6984:8)
    at F.listener (/home/grega/Projects/Work/totaljs_project/node_modules/total.js/index.js:6833:4)
    at emitTwo (events.js:135:12)
    at emit (events.js:224:6)
    at parserOnIncoming (_http_server.js:619:11)
    at parserOnHeadersComplete (_http_common.js:117:22)

**Comment by petersirka** [comment]
Hi @gmenih341,
can I see the code on this line `/manager.js:1675:10`?

Which version of Total.js + jComponent do you use? BTW: instead of `$.components.GET()` use `AJAX('GET /api/endpoint/', options, function(response) {`.

Thank you!

**Comment by gmenih341** [comment]
@petersirka The line 1675:10 is the line I pasted, `GETSCHEMA('Product').query(self.query, self.callback);`

TotalJS version is 2.9.0, and I can't find jComponent being explicitly installed.

**Comment by petersirka** [comment]
@gmenih341 please write me the whole exception. .

**Comment by gmenih341** [comment]
There's no exception. It just calls the endpoint handler 4 times, and I get 408 status code on my api calls because of it.

**Comment by petersirka** [comment]
But before the line below is something:
`at endpoint_handler (/home/grega/Projects/Work/totaljs_project/controllers/manager.js:1675:10)`

And I need see it and send me the content `.setQuery()` of Product schema.

**Comment by petersirka** [comment]
I'm going to travel, so I will back around 3 hours.

**Comment by molda** [comment]
You are missing parenthesis after `self.callback`

   GETSCHEMA('Product').query(self.query, self.callback());

self.callback needs to be called because it returns a function depending on content type, so for json it will use self.json and for view self.view

**Comment by gmenih341** [comment]
@molda ah, thanks for that info. I thought there was an error in code, so I actually removed the parenthesis. This, however, still doesn't solve my issue :/

**Comment by molda** [comment]
Try to replace self.callback() with a function:

    GETSCHEMA('Product').query(self.query, function (err, response) {
        console.log(err, response);
        self.json(response);
    });

Do you see the results in the console?

**Comment by gmenih341** [comment]
Yep, I see the `console.log` being called multiple times.

**Comment by molda** [comment]
Can you show us your controller??

**Comment by petersirka** [comment]
Is there any news?
