### ISSUE TITLE
RESTBuilder.make() is giving this weird Error 

### ISSUE THREAD

**Issue by nabeelalis** [totaljs/framework#631]
> ======= 2018-04-17 15:50:15: sparkSessionRoutes ---> TypeError [ERR_INVALID_ARG_TYPE]: The "name" argument must be of type string. Received type null (http://localhost:8000/v1/session) TypeError [ERR_INVALID_ARG_TYPE]: The "name" argument must be of type string. Received type null
>     at Resolver.queryA [as resolve4] (dns.js:268:13)
>     at Object.exports.resolve (D:\work\scythe\node_modules\total.js\utils.js:300:6)
>     at Object.exports.request (D:\work\scythe\node_modules\total.js\utils.js:569:11)
>     at RESTBuilder.exec (D:\work\scythe\node_modules\total.js\builders.js:4070:11)
>     at D:\work\scythe\controllers\sparkSessionController.js:129:17
>     at Function.RESTBuilder.make (D:\work\scythe\node_modules\total.js\builders.js:3728:2)
>     at D:\work\scythe\controllers\sparkSessionController.js:124:19
>     at internals.Object._validateWithOptions (D:\work\scythe\node_modules\joi\lib\types\any\index.js:671:20)
>     at module.exports.internals.Any.root.validate (D:\work\scythe\node_modules\joi\lib\index.js:139:23)
>     at Controller.create (D:\work\scythe\controllers\sparkSessionController.js:114:7)
>     at IncomingMessage.PROTO.$total_execute2 (D:\work\scythe\node_modules\total.js\index.js:14078:32)
>     at IncomingMessage.PROTO.$total_execute (D:\work\scythe\node_modules\total.js\index.js:14046:9)
>     at IncomingMessage.PROTO.$total_authorize (D:\work\scythe\node_modules\total.js\index.js:14166:10)
>     at D:\work\scythe\node_modules\total.js\index.js:14329:9
>     at Framework.F.onAuthorize (D:\work\scythe\definitions\auth.js:50:3)
>     at IncomingMessage.PROTO.$total_prepare (D:\work\scythe\node_modules\total.js\index.js:14320:6)
>     at IncomingMessage.PROTO.$total_end2 (D:\work\scythe\node_modules\total.js\index.js:14242:8)
>     at IncomingMessage.emit (events.js:160:13)
>     at endReadableNT (_stream_readable.js:1101:12)
>     at process._tickCallback (internal/process/next_tick.js:152:19)``

This is only happening when I try to use the RESTBuilder.

**Comment by nabeelalis** [comment]
Nvm
