### ISSUE TITLE
SMTP connect error

### ISSUE THREAD

**Issue by NikitaRadkov** [totaljs/framework#703]
Hello! I installed eshop on the server, and tried to connect the smtp server, and it seemed to be connected. But when you try to send a message, such as restoring a user password, error 408 appears in the console.

======= 2019-03-14 20:58:15: mail-smtp ---> Error: 408: Request Timeout (mail.sew-opt.ru) Error: 408: Request Timeout
    at Socket.<anonymous> (/home/nikita/eshop/node_modules/total.js/mail.js:615:13)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:348:8)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

Could you help solve the problem?

**Comment by petersirka** [comment]
Hi, this means that SMTP server doesn't respond. Are you sure your SMTP is valid?

**Comment by NikitaRadkov** [comment]
I think yes. When i write the command:  cat ~/test_message | mail -s 'Test email subject line' -r from_field mymail@example.com
I get an email. 

postfix/postfix-script: the Postfix mail system is running: PID: 9611

**Comment by petersirka** [comment]
I need to test your SMTP server. Can you send me it on my email?
