### ISSUE TITLE
total.js v3.4 error

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/framework#746]
I'am userd SCHEDULE to Error

======= 2020-02-25 11:15:09: TypeError: F.snapshotstats is not a function TypeError: F.snapshotstats is not a function
    at FrameworkCacheProto.recycle (/opt/flow/node_modules/total.js/index.js:11283:33)
    at Timeout._onTimeout (/opt/flow/node_modules/total.js/index.js:11187:44)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by petersirka** [comment]
Hi @KangGeunSu,
I have fixed it. Please install latet beta version `$ npm install total.js@beta`. It's stable and hot-fix fill be next week (I belive).

**Comment by KangGeunSu** [comment]
Thank you~
