### ISSUE TITLE
I found something that might have a problem

### ISSUE THREAD

**Issue by luasenvy** [totaljs/framework#748]
I am using nuxt.js with total.js (nodejs 12.16.1)

1. nodejs 12.16.1 built-in `Array.prototype.find` is return `undefined` when not found item.

2. nuxt has depends 
`nuxt -> execa -> human-signals`

3. `human-signals` module is using `Array.find()` and after compare with `undefined`.

4. but, totaljs already extends `Array.prototype.find` to return `null`

5. so, `human-signals` module return a error.
```
TypeError: Cannot destructure property 'name' of 'signal' as it is null.
    at getSignalByNumber (/app/node_modules/human-signals/build/src/main.js:44:7)
    at /app/node_modules/human-signals/build/src/main.js:32:1
    at Function.from (<anonymous>)
    at getSignalsByNumber (/app/node_modules/human-signals/build/src/main.js:31:22)
    at Object.<anonymous> (/app/node_modules/human-signals/build/src/main.js:70:23)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
```

`human-signals` module is compare with `undefined` but value is `null`:
![image](https://user-images.githubusercontent.com/24634713/77130407-37640b80-6a9b-11ea-8555-5b3f7aee502d.png)

i resolve this problem redefine `Array.prototype.find()` return `undefined` before `require('nuxt')`:
```
    Array.prototype.find = function(...args) {
      let index = this.findIndex(...args)
      if (index >= 0) return index >= 0 ? this[index] : void 0
    }

    const { Nuxt, Builder } = require('nuxt')
```

i'm not sure this code not have a side effect for total.js but, well worked.

if has a better solution, please guide me.

feel free close this issue

thanks :)

**Comment by petersirka** [comment]
Hi, it's OK. `.find()` is very old function. I renamed it to `.findItem()` a long time ago but it still alive because of backward compatibility.

So don't worry to overwrite it.

**Comment by petersirka** [comment]
BTW: I have added `deprecated` warning to `Array.prototype.find()` method. So it will be removed in Total.js `v4`.

**Comment by luasenvy** [comment]
thank you for answer.
I'll refer to that :)
