### ISSUE TITLE
ERR_INVALID_ARG_TYPE node 14.0.0

### ISSUE THREAD

**Issue by cyberquito** [totaljs/framework#756]
Hello,

I will like to report an error with the latest version from node: 14.0.0.

I'm developing on macOS Catalina 10.15.3.

Here's the output:

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (4391)
    at Object.writeFileSync (fs.js:1380:5)
    at app (/Users/quito/Sites/core/backend/node_modules/total.js/debug.js:459:7)
    at Immediate.runwatching [as _onImmediate] (/Users/quito/Sites/core/backend/node_modules/total.js/debug.js:489:3)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by petersirka** [comment]
Hi, yes - I have fixed that bug. Just download latest beta version `$ npm install total.js@beta`. It's stable.

**Comment by cyberquito** [comment]
That was fast. Thanks Peter.

**Comment by petersirka** [comment]
No no, I fixed it 6 days ago... Maybe a next week will be a new release of Total.js framework.
Thx.
